# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: JeniusTech Engineering
author: JeniusTech Engineering
description: Jenius, bank reinvented
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jenius.tech" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Social media
twitter_username: 'jeniusTech'
twitter_image:
facebook_app_id:
facebook_image:
google_analytics: 'UA-100082437-1'
comments: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
#jekyll-archives:
authors:
  dedenf:
    name: "Deden Fathurahman"
    uri: https://notes.dedenf.com
    email: me@dedenf.com
    twitter: dedenf
    description: "Tufte emphasizes tight integration of graphics with text. Data, graphs, and figures are kept with the text that discusses them. In print, this means they are not relegated to a separate page. On the web, that means readability of graphics and their accompanying text without extra clicks, tab-switching, or scrolling."