# Site Settings

paginate:     5
permalink:    /:year/:month/:day/:title/
highlighter:  pygments
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
gems:                [jekyll-paginate]
