# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jenius
tagline:             'Tech'
description:         'lalala'
url:                 https://jenius.tech
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jenius Team
  url:               https://twitter.com/jeniusConnect
  email:             hi@jenius.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
