title:  Jenius
tagline:  Engineering
author:
  name: "Jenius Engineering"
  twitter:  jeniusTech

menu:
- {name: 'About', url: 'about'}
- {name: 'Archives', url: 'writing'}

jenius_link: 'https://jenius.com'

social:
- {icon: 'github', link: 'https://www.github.com/jeniusTeam'}
- {icon: 'twitter', link: 'https://twitter.com/jeniusTech'}
- {icon: 'instagram', link: 'https://instagram.com/jeniusConnect'}
- {icon: 'envelope', link: 'mailto:hi@jenius.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
